### ISSUE TITLE
Set Correct `ProviderID` Format in `cloud-provider-metal`

### ISSUE THREAD

**Issue by afritzler** [ironcore-dev/cloud-provider-metal#17]
### Problem Statement

Currently, the `ProviderID` in `Node` objects for the `cloud-provider-metal` is set in the following format:

- **Current format:**  
  `providerID: metal://<namespace>/<serverclaim-name>`

This format is inadequate for uniquely identifying nodes, particularly in scenarios where namespace and server claim names might be duplicated across clusters. 

### Proposed Solutions

We need to modify the `ProviderID` format to ensure unique identification of nodes. Below are the alternative formats proposed:

1. **Option 1:**  
   `providerID: metal://<namespace>/<serverclaim-name>/<serverclaim-uid>`
   
   - **Pros:** Uniquely identifies each `serverclaim` by including its UID, even within the same namespace.
   - **Cons:** Increases the length of the `ProviderID`.

2. **Option 2:**  
   `providerID: metal://<cluster-identity>/<namespace>/<serverclaim-name>`
   
   - **Pros:** Ensures uniqueness across clusters by incorporating a cluster-wide identifier.
   - **Cons:** Does not account for multiple claims within the same namespace that might have the same name.

3. **Option 3:**  
   `providerID: metal://<cluster-identity>/<namespace>/<serverclaim-name>/<serverclaim-uid>`
   
   - **Pros:** Combines both cluster identity and the server claim's UID for maximum uniqueness.
   - **Cons:** Longest format, may lead to issues if there's a character limit on `ProviderID`.

### Recommended Action

- **Primary Recommendation:** Adopt **Option 3** (`providerID: metal://<cluster-identity>/<namespace>/<serverclaim-name>/<serverclaim-uid>`) as it offers the most comprehensive solution for unique node identification across different clusters and namespaces.
  
### Definition of Done

- Update the `ProviderID` format in the `cloud-provider-metal` implementation to the agreed-upon format.
- Ensure backward compatibility with existing `ProviderID` formats or provide a clear migration path.
- Update documentation to reflect the new `ProviderID` format and its usage.
- Conduct thorough testing to verify that the new format correctly identifies nodes without introducing any regressions or new issues.

**Comment by Nuckal777** [comment]
What speaks against `metal://<namespace>/<serverclaim-uid>`? The providerID does not need to be human readable I think. Efficient retrieval in the cloud-controller-manager can be achieved with [indexing](https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.19.0/pkg/client#FieldIndexer) and [filtering](https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.19.0/pkg/client#MatchingFields) on the index.

**Comment by afritzler** [comment]
My thought was that doing a string split of `metal://<namespace>/<serverclaim-name>/<serverclaim-uid>` is way easier as `/` can not be part of the name of a resource or it's namespace (but `-` can).

**Comment by Nuckal777** [comment]
With cluster identity you mean the name of the cluster managed by the cloud-provider? If in doubt, it can be included. How do we get the identity? From the kubeconfig?

**Comment by hardikdr** [comment]
I would suggest using a server UUID in the ProviderID for global uniqueness, like AWS does with instance IDs. It will ensure, we can always track back to the exact machine, even if there are disruptive changes in the Kubernetes-stack.

Adding a hint about the region or zone would also be quite nice.

**Comment by afritzler** [comment]
Well I would rather refer to the `ServerClaim` UUID as this `providerID` is used to get the corresponding object responsible for this `Node`. In our case it is the `ServerClaim`.

**Comment by afritzler** [comment]
> With cluster identity you mean the name of the cluster managed by the cloud-provider? If in doubt, it can be included. How do we get the identity? From the kubeconfig?

You provide the cluster identity via the `cloudprovider.conf` to the CCM. But thinking about it - we can not guarantee global uniqueness across various environments that those IDs will be unique. E.g. cluster in DC1 can have the same name as a cluster in DC2. I guess we can scrap this `cluster-identity` idea.

**Comment by afritzler** [comment]
I would favor to go with option 1 here. Are there any objections?
